# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 13 23:19:43 2024
# ------------------------------------------------

package:
  name: zipp
  version: 3.20.0
source:
  sha256: 0145e43d89664cfe1a2e533adc75adafed82fe2da404b4bbb6b026c0157bdb31
  url: https://pypi.io/packages/source/z/zipp/zipp-3.20.0.tar.gz
build:
  noarch: python
  number: '0'
  script: '/home/conda/feedstock_root/build_artifacts/zipp_1723591248676/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps --ignore-installed -vv '
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.7.4 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4bc722e_2
    - packaging 24.1 pyhd8ed1ab_0
    - pip 24.2 pyhd8ed1ab_0
    - python 3.12.5 h2ad013b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 72.1.0 pyhd8ed1ab_0
    - setuptools-scm 6.4.2 pyhd8ed1ab_0
    - setuptools_scm 6.4.2 hd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - toml 0.10.2 pyhd8ed1ab_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.8
test:
  commands:
    - python -m unittest tests/test_path.py
    - pip check
  imports:
    - zipp
  requires:
    - importlib_metadata
    - jaraco.functools
    - jaraco.itertools
    - jaraco.test
    - more-itertools
    - pip
  source_files:
    - tests
about:
  dev_url: https://github.com/jaraco/zipp
  doc_url: https://zipp.readthedocs.io/en/latest
  home: https://github.com/jaraco/zipp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pathlib-compatible Zipfile object wrapper
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240813.2.1
  recipe-maintainers:
    - jan-janssen
    - nehaljwani
  remote_url: https://github.com/conda-forge/zipp-feedstock
  sha: 8eb2be3b863e16aec8759d5b1027a03ef5445e26
