# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Aug 19 17:20:10 2024
# ------------------------------------------------

package:
  name: pyzmq
  version: 26.1.1
source:
  sha256: a7db05d8b7cd1a8c6610e9e9aa55d525baae7a44a43e18bc3260eb3f92de96c6
  url: https://pypi.io/packages/source/p/pyzmq/pyzmq-26.1.1.tar.gz
build:
  number: '0'
  string: py310h7d2b5bf_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_0
    - bzip2 1.0.8 h4bc722e_7
    - c-ares 1.32.3 h4bc722e_0
    - ca-certificates 2024.7.4 hbcca054_0
    - cmake 3.30.2 hf8c4bd3_0
    - gcc_impl_linux-64 12.4.0 hb2e57f8_0
    - gcc_linux-64 12.4.0 h6b7512a_0
    - gxx_impl_linux-64 12.4.0 h613a52c_0
    - gxx_linux-64 12.4.0 h8489865_0
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libcurl 8.9.1 hdb1bdb2_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libexpat 2.6.2 h59595ed_0
    - libgcc-devel_linux-64 12.4.0 ha4f9413_100
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libnghttp2 1.58.0 h47da74e_1
    - libsanitizer 12.4.0 h46f95d5_0
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-devel_linux-64 12.4.0 ha4f9413_100
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libuv 1.48.0 hd590300_0
    - libzlib 1.3.1 h4ab18f5_1
    - make 4.3 hd18ef5c_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4bc722e_2
    - pkg-config 0.29.2 h4bc722e_1009
    - rhash 1.4.4 hd590300_0
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h0c530f3_0
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.6 ha6fb4c9_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.7.4 hbcca054_0
    - cython 3.0.11 py310hea249c9_0
    - exceptiongroup 1.2.2 pyhd8ed1ab_0
    - importlib-metadata 8.2.0 pyha770c72_0
    - importlib-resources 6.4.3 pyhd8ed1ab_0
    - importlib_resources 6.4.3 pyhd8ed1ab_0
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libedit 3.1.20191231 he28a2e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libnsl 2.0.1 hd590300_0
    - libsodium 1.0.18 h36c2ea0_1
    - libsqlite 3.46.0 hde9e2c9_0
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4bc722e_2
    - packaging 24.1 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.2 pyhd8ed1ab_0
    - python 3.10.14 hd12c33a_0_cpython
    - python_abi 3.10 5_cp310
    - readline 8.2 h8228510_1
    - scikit-build-core 0.10.3 pyh4af843d_0
    - setuptools 72.1.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.12.2 hd8ed1ab_0
    - typing_extensions 4.12.2 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zeromq 4.3.5 h75354e8_4
    - zipp 3.20.0 pyhd8ed1ab_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc-ng >=12
    - libsodium >=1.0.18,<1.0.19.0a0
    - libsodium >=1.0.18,<1.0.19.0a0
    - libstdcxx-ng >=12
    - python >=3.10,<3.11.0a0
    - python_abi 3.10.* *_cp310
    - zeromq >=4.3.5,<4.4.0a0
test:
  commands:
    - pip check
    - pytest tests/test_socket.py
  imports:
    - zmq
    - zmq.backend.cython
    - zmq.devices.monitoredqueue
  requires:
    - pip
    - pytest
  source_files:
    - pyproject.toml
    - pytest.ini
    - tests
about:
  home: https://github.com/zeromq/pyzmq
  license: BSD-3-Clause
  license_file:
    - LICENSE.md
  summary: Python bindings for zeromq
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240819.2.1
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - jakirkham
    - jan-janssen
    - minrk
    - msarahan
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/pyzmq-feedstock
  sha: e6cc9a0e45512fa05cc601e49a70bc1dedf5f5f7
