# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri May 31 19:45:54 2024
# ------------------------------------------------

package:
  name: pymeep
  version: 1.29.0
source:
  fn: meep-1.29.0.tar.gz
  sha256: 68279f862cf9342a6e0f2023667d6a6ac7c1eafe46663705519772f312412194
  url: https://github.com/NanoComp/meep/releases/download/v1.29.0/meep-1.29.0.tar.gz
build:
  number: '3'
  string: mpi_mpich_py310h1234567_3
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha1999f0_1
    - binutils_linux-64 2.40 hdade7a5_3
    - gcc_impl_linux-64 12.3.0 h58ffeeb_7
    - gcc_linux-64 12.3.0 h6477408_3
    - gfortran_impl_linux-64 12.3.0 h1645026_7
    - gfortran_linux-64 12.3.0 h617cb40_3
    - gxx_impl_linux-64 12.3.0 h2a574ab_7
    - gxx_linux-64 12.3.0 h4a1b8e8_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 hf3520f5_1
    - libgcc-devel_linux-64 12.3.0 h0223996_107
    - libgcc-ng 13.2.0 h77fa898_7
    - libgfortran5 13.2.0 hca663fb_7
    - libgomp 13.2.0 h77fa898_7
    - libsanitizer 12.3.0 hb8811af_7
    - libstdcxx-devel_linux-64 12.3.0 h0223996_107
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - c-ares 1.28.1 hd590300_0
    - ca-certificates 2024.2.2 hbcca054_0
    - fftw 3.3.10 mpi_mpich_h5537406_8
    - gsl 2.7 he838d99_0
    - harminv 1.4.2 hc567f7b_0
    - hdf5 1.14.2 mpi_mpich_ha2c2bf8_0
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - ld_impl_linux-64 2.40 hf3520f5_1
    - libaec 1.1.3 h59595ed_0
    - libblas 3.9.0 5_h92ddd45_netlib
    - libcblas 3.9.0 5_h92ddd45_netlib
    - libctl 4.5.1 h7f98852_0
    - libcurl 8.8.0 hca28451_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgdsii 0.21 h4bd325d_4
    - libgfortran-ng 13.2.0 h69a702a_7
    - libgfortran5 13.2.0 hca663fb_7
    - libgomp 13.2.0 h77fa898_7
    - liblapack 3.9.0 5_h92ddd45_netlib
    - libnghttp2 1.58.0 h47da74e_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-ng 13.2.0 hc0a3c3a_7
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 h4ab18f5_6
    - make 4.3 hd18ef5c_1
    - mpb 1.11.1 mpi_mpich_h5eb1b22_4
    - mpi 1.0 mpich
    - mpi4py 3.1.6 py310hcb86253_1
    - mpich 4.2.1 h846660c_100
    - ncurses 6.5 h59595ed_0
    - numpy 1.22.4 py310h4ef5377_0
    - openssl 3.3.0 h4ab18f5_3
    - python 3.10.14 hd12c33a_0_cpython
    - python_abi 3.10 4_cp310
    - readline 8.2 h8228510_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 h4ab18f5_6
    - zstd 1.5.6 ha6fb4c9_0
  run:
    - _openmp_mutex
    - fftw * mpi_mpich_*
    - fftw >=3.3.10,<4.0a0
    - gsl >=2.7,<2.8.0a0
    - h5py * mpi_mpich_*
    - harminv >=1.4.1
    - hdf5 * mpi_mpich_*
    - hdf5 >=1.14.2,<1.14.3.0a0 mpi_mpich_*
    - libblas >=3.9.0,<4.0a0
    - libcblas >=3.9.0,<4.0a0
    - libctl >=4.5.0
    - libgcc-ng >=12
    - libgdsii >=0.21
    - libgfortran-ng
    - libgfortran5 >=12.3.0
    - liblapack >=3.9.0,<4.0a0
    - libopenblas
    - libstdcxx-ng >=12
    - matplotlib-base
    - mpb * mpi_mpich_*
    - mpb >=1.11 mpi_mpich_*
    - mpi4py >=3.0
    - mpich >=4.2.1,<5.0a0
    - numpy >=1.22.4,<2.0a0
    - python >=3.10,<3.11.0a0
    - python_abi 3.10.* *_cp310
    - scipy
    - zlib
about:
  dev_url: https://github.com/NanoComp/meep
  doc_url: https://meep.readthedocs.io
  home: https://github.com/NanoComp/meep
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Free finite-difference time-domain (FDTD) software for electromagnetic
    simulations
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240531.11.1
  recipe-maintainers:
    - oskooi
  remote_url: https://github.com/conda-forge/pymeep-feedstock
  sha: 31c5613e695d91a37646ba9c42ef9074f1a2397e
