# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jul 29 17:11:29 2024
# ------------------------------------------------

package:
  name: conda
  version: 24.7.1
source:
  fn: conda-24.7.1.tar.gz
  sha256: bba5ba84425a76b738a433511bfaf81420548b869429ef5c45019e526869e87b
  url: https://github.com/conda/conda/releases/download/24.7.1/conda-24.7.1.tar.gz
build:
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/conda_1722273156164/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --no-build-isolation -vv && /home/conda/feedstock_root/build_artifacts/conda_1722273156164/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m conda init --install
  string: py312h7900ff3_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - boltons 24.0.0 pyhd8ed1ab_0
    - brotli-python 1.1.0 py312h30efb56_1
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.7.4 hbcca054_0
    - certifi 2024.7.4 pyhd8ed1ab_0
    - cffi 1.16.0 py312hf06ca03_0
    - charset-normalizer 3.3.2 pyhd8ed1ab_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - editables 0.5 pyhd8ed1ab_0
    - h2 4.1.0 pyhd8ed1ab_0
    - hatch-vcs 0.4.0 pyhd8ed1ab_0
    - hatchling 1.25.0 pyhd8ed1ab_0
    - hpack 4.0.0 pyh9f0ad1d_0
    - hyperframe 6.0.1 pyhd8ed1ab_0
    - idna 3.7 pyhd8ed1ab_0
    - importlib-metadata 8.2.0 pyha770c72_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - menuinst 2.1.1 py312h7900ff3_0
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4bc722e_2
    - packaging 24.1 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.5.0 pyhd8ed1ab_0
    - pycparser 2.22 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - python 3.12.4 h194c7f8_0_cpython
    - python_abi 3.12 4_cp312
    - readline 8.2 h8228510_1
    - requests 2.32.3 pyhd8ed1ab_0
    - ruamel.yaml 0.18.6 py312h98912ed_0
    - ruamel.yaml.clib 0.2.8 py312h98912ed_0
    - setuptools 71.0.4 pyhd8ed1ab_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - tqdm 4.66.4 pyhd8ed1ab_0
    - trove-classifiers 2024.7.2 pyhd8ed1ab_0
    - typing-extensions 4.12.2 hd8ed1ab_0
    - typing_extensions 4.12.2 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - urllib3 2.2.2 pyhd8ed1ab_1
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zipp 3.19.2 pyhd8ed1ab_0
    - zstandard 0.23.0 py312h3483029_0
    - zstd 1.5.6 ha6fb4c9_0
  run:
    - archspec >=0.2.3
    - boltons >=23.0.0
    - charset-normalizer
    - conda-libmamba-solver >=23.11.0
    - conda-package-handling >=2.2.0
    - distro >=1.5.0
    - frozendict >=2.4.2
    - jsonpatch >=1.32
    - menuinst >=2
    - packaging >=23.0
    - platformdirs >=3.10.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - setuptools >=60.0.0
    - tqdm >=4
    - truststore >=0.8.0
    - zstandard >=0.19.0
  run_constrained:
    - conda-build >=24.3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
test:
  downstreams: null
  files:
    - commands_to_test.sh
    - test_runner.sh
  imports:
    - conda
    - conda_env
  requires:
    - mock
    - pexpect
    - responses
about:
  description: 'Conda is an open source package management system and environment

    management system for installing multiple versions of software packages

    and their dependencies and switching easily between them. It works on

    Linux, OS X and Windows, and was created for Python programs but can

    package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://conda.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240729.1.1
  recipe-maintainers:
    - beeankha
    - dbast
    - isuruf
    - jakirkham
    - jezdez
    - kenodegard
    - mbargull
    - ocefpaf
  remote_url: https://github.com/conda-forge/conda-feedstock
  sha: e3176f40804a60860ffb7b7f24856af58259f4d1
