# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Aug 23 13:13:15 2024
# ------------------------------------------------

package:
  name: libxcb
  version: '1.16'
source:
  fn: libxcb-1.16.tar.bz2
  patches: null
  sha256: bc0f75f84b28e6496a19a1d094d7e47def861a50cb7cce5b23b62eecdc2a4479
  url: https://xorg.freedesktop.org/archive/individual/lib/libxcb-1.16.tar.gz
build:
  detect_binary_files_with_prefix: true
  number: '1'
  run_exports:
    - libxcb >=1.16,<1.17.0a0
  string: hb9d3cd8_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - autoconf 2.71 pl5321h2b4cb7a_1
    - automake 1.17 pl5321ha770c72_0
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_0
    - gcc_impl_linux-64 13.3.0 hfea6d02_0
    - gcc_linux-64 13.3.0 hc28eda2_0
    - gettext 0.22.5 he02047a_3
    - gettext-tools 0.22.5 he02047a_3
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libasprintf 0.22.5 he8f35ee_3
    - libasprintf-devel 0.22.5 he8f35ee_3
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_100
    - libgcc-ng 14.1.0 h77fa898_0
    - libgettextpo 0.22.5 he02047a_3
    - libgettextpo-devel 0.22.5 he02047a_3
    - libgomp 14.1.0 h77fa898_0
    - libsanitizer 13.3.0 heb74ff8_0
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libtool 2.4.7 h27087fc_0
    - libxcrypt 4.4.36 hd590300_1
    - m4 1.4.18 h516909a_1001
    - make 4.4.1 hb9d3cd8_0
    - perl 5.32.1 7_hd590300_perl5
    - pkg-config 0.29.2 h4bc722e_1009
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h0c530f3_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.7.4 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 hb9d3cd8_3
    - pthread-stubs 0.4 h36c2ea0_1001
    - python 3.12.5 h2ad013b_0_cpython
    - python_abi 3.12 5_cp312
    - readline 8.2 h8228510_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - xcb-proto 1.16.0 py312h98912ed_1
    - xorg-libxau 1.0.11 hd590300_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-util-macros 1.19.3 h7f98852_0
    - xorg-xproto 7.0.31 h7f98852_1007
    - xz 5.2.6 h166bdaf_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc-ng >=13
    - pthread-stubs
    - xorg-libxau >=1.0.11,<2.0a0
    - xorg-libxdmcp
test:
  commands:
    - test -f $PREFIX/lib/libxcb.so
    - test -f $PREFIX/lib/libxcb-composite.so
    - test -f $PREFIX/lib/libxcb-damage.so
    - test -f $PREFIX/lib/libxcb-dpms.so
    - test -f $PREFIX/lib/libxcb-dri2.so
    - test -f $PREFIX/lib/libxcb-glx.so
    - test -f $PREFIX/lib/libxcb-present.so
    - test -f $PREFIX/lib/libxcb-randr.so
    - test -f $PREFIX/lib/libxcb-record.so
    - test -f $PREFIX/lib/libxcb-res.so
    - test -f $PREFIX/lib/libxcb-screensaver.so
    - test -f $PREFIX/lib/libxcb-shape.so
    - test -f $PREFIX/lib/libxcb-shm.so
    - test -f $PREFIX/lib/libxcb-sync.so
    - test -f $PREFIX/lib/libxcb-xf86dri.so
    - test -f $PREFIX/lib/libxcb-xfixes.so
    - test -f $PREFIX/lib/libxcb-xinerama.so
    - test -f $PREFIX/lib/libxcb-xkb.so
    - test -f $PREFIX/lib/libxcb-xtest.so
    - test -f $PREFIX/lib/libxcb-xv.so
    - test -f $PREFIX/lib/libxcb-xvmc.so
    - test -f $PREFIX/lib/libxcb-dri3.so
    - test -f $PREFIX/lib/libxcb-render.so
    - test -f $PREFIX/lib/libxcb-xinput.so
about:
  home: http://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is the C-language Binding (XCB) package to the X Window System protocol
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240823.1.1
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - pkgw
  remote_url: https://github.com/conda-forge/libxcb-feedstock
  sha: 006ecd774ae2e621e1819f9071222c3b2a8bf097
