# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Jan 18 18:17:11 2024
# ------------------------------------------------

package:
  name: zeromq
  version: 4.3.5
source:
  fn: zeromq-4.3.5.tar.gz
  patches:
    - 001-windows-install.patch
  sha256: 6653ef5910f17954861fe72332e68b03ca6e4d9c7160eb3a8de5a5a913bfab43
  url: https://github.com/zeromq/libzmq/releases/download/v4.3.5/zeromq-4.3.5.tar.gz
build:
  number: '0'
  run_exports:
    - zeromq >=4.3.5,<4.4.0a0
  string: h6a678d5_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - autoconf 2.71 pl5340h5eee18b_0
    - automake 1.16.5 pl5340h06a4308_1
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gdbm 1.18 hd4cb3f1_4
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libtool 2.4.6 h6a678d5_1009
    - m4 1.4.18 h4e445db_0
    - make 4.2.1 h1bed415_1
    - ncurses 6.4 h6a678d5_0
    - patch 2.7.6 h7b6447c_1001
    - perl 5.34.0 h5eee18b_2
    - pkg-config 0.29.2 h1bed415_8
    - readline 8.2 h5eee18b_0
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libsodium 1.0.18 h7b6447c_0
    - libstdcxx-ng 11.2.0 h1234567_1
  run:
    - libgcc-ng >=11.2.0
    - libsodium >=1.0.18,<1.0.19.0a0
    - libsodium >=1.0.18,<1.0.19.0a0
    - libstdcxx-ng >=11.2.0
about:
  description: 'The ZeroMQ lightweight messaging kernel is a library which extends
    the standard socket

    interfaces with features traditionally provided by specialised messaging middleware
    products.

    ZeroMQ sockets provide an abstraction of asynchronous message queues, multiple
    messaging

    patterns, message filtering (subscriptions), seamless access to multiple transport
    protocols and more.

    '
  dev_url: https://github.com/zeromq/libzmq
  doc_url: https://zeromq.org/get-started/
  home: https://zeromq.org
  license: MPL-2.0
  license_family: Other
  license_file: LICENSE
  summary: A high-performance asynchronous messaging library.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 013ef8a2-3cfc-4d92-bbfe-690d49bf1f09
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - davidbrochart
    - jakirkham
    - minrk
  remote_url: git@github.com:AnacondaRecipes/zeromq-feedstock.git
  sha: dfa618872014ed6675082a7b7ea030cbbc86ae69
