# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Aug  5 01:06:07 2024
# ------------------------------------------------

package:
  name: libdeflate
  version: '1.21'
source:
  sha256: 50827d312c0413fbd41b0628590cd54d9ad7ebf88360cba7c0e70027942dbd01
  url: https://github.com/ebiggers/libdeflate/archive/v1.21.tar.gz
build:
  number: '0'
  run_exports:
    - libdeflate >=1.21,<1.22.0a0
  string: h4bc722e_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_0
    - bzip2 1.0.8 h4bc722e_7
    - c-ares 1.32.3 h4bc722e_0
    - ca-certificates 2024.7.4 hbcca054_0
    - cmake 3.30.2 hf8c4bd3_0
    - gcc_impl_linux-64 12.4.0 hb2e57f8_0
    - gcc_linux-64 12.4.0 h6b7512a_0
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libcurl 8.9.1 hdb1bdb2_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libexpat 2.6.2 h59595ed_0
    - libgcc-devel_linux-64 12.4.0 ha4f9413_100
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libnghttp2 1.58.0 h47da74e_1
    - libsanitizer 12.4.0 h46f95d5_0
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libuv 1.48.0 hd590300_0
    - libzlib 1.3.1 h4ab18f5_1
    - make 4.3 hd18ef5c_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4bc722e_2
    - rhash 1.4.4 hd590300_0
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h0c530f3_0
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.6 ha6fb4c9_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc-ng >=12
test:
  commands:
    - test ! -f ${PREFIX}/lib/libdeflate.a
    - test -f ${PREFIX}/lib/libdeflate${SHLIB_EXT}
    - test -f ${PREFIX}/include/libdeflate.h
    - libdeflate-gzip -h
    - libdeflate-gunzip -h
about:
  home: https://github.com/ebiggers/libdeflate
  license: MIT
  license_file: COPYING
  summary: libdeflate is a library for fast, whole-buffer DEFLATE-based compression
    and decompression.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240804.3.1
  recipe-maintainers:
    - dpryan79
    - hmaarrfk
    - rhpvorderman
  remote_url: https://github.com/conda-forge/libdeflate-feedstock
  sha: b29c31d1f0224df9a483af6cfe994e640f393201
