# This file created by conda-build 24.5.1
# ------------------------------------------------

package:
  name: mpich
  version: 4.2.2
source:
  fn: mpich-4.2.2.tar.gz
  patches:
    - libfrabric-osx-memsize.patch
  sha256: 883f5bb3aeabf627cb8492ca02a03b191d09836bbe0f599d8508351179781d41
  url: https://www.mpich.org/static/downloads/4.2.2/mpich-4.2.2.tar.gz
build:
  number: 101
  run_exports:
    - mpich >=4.2.2,<5.0a0
  string: h4a7f18d_101
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - autoconf 2.71 pl5321h2b4cb7a_1
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_0
    - gcc_impl_linux-64 12.4.0 hb2e57f8_0
    - gcc_linux-64 12.4.0 h6b7512a_0
    - gfortran_impl_linux-64 12.4.0 hc568b83_0
    - gfortran_linux-64 12.4.0 hd748a6a_0
    - gxx_impl_linux-64 12.4.0 h557a472_0
    - gxx_linux-64 12.4.0 h8489865_0
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc-devel_linux-64 12.4.0 ha4f9413_100
    - libgcc-ng 14.1.0 h77fa898_0
    - libgfortran5 14.1.0 hc5f4f2c_0
    - libgomp 14.1.0 h77fa898_0
    - libsanitizer 12.4.0 h46f95d5_0
    - libstdcxx-devel_linux-64 12.4.0 ha4f9413_100
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libtool 2.4.7 h27087fc_0
    - libxcrypt 4.4.36 hd590300_1
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - perl 5.32.1 7_hd590300_perl5
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h0c530f3_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_0
    - gcc_impl_linux-64 12.4.0 hb2e57f8_0
    - gcc_linux-64 12.4.0 h6b7512a_0
    - gfortran_impl_linux-64 12.4.0 hc568b83_0
    - gfortran_linux-64 12.4.0 hd748a6a_0
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc-devel_linux-64 12.4.0 ha4f9413_100
    - libgcc-ng 14.1.0 h77fa898_0
    - libgfortran-ng 14.1.0 h69a702a_0
    - libgfortran5 14.1.0 hc5f4f2c_0
    - libgomp 14.1.0 h77fa898_0
    - libsanitizer 12.4.0 h46f95d5_0
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h0c530f3_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc-ng >=12
    - libgfortran-ng
    - libgfortran5 >=12.4.0
    - libstdcxx-ng >=12
    - mpi 1.0 mpich
test:
  files:
    - mpiexec.sh
    - tests/helloworld.sh
  script: run_test.sh
about:
  description: 'MPICH is a high performance and widely portable implementation of
    the

    Message Passing Interface (MPI) standard.

    '
  dev_url: https://github.com/pmodels/mpich
  doc_url: https://www.mpich.org/documentation/guides
  home: https://www.mpich.org/
  license: LicenseRef-MPICH
  license_family: Other
  license_file: COPYRIGHT
  summary: A high performance widely portable implementation of the MPI standard.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240731.2.1
  recipe-maintainers:
    - astrofrog
    - bekozi
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
  remote_url: https://github.com/conda-forge/mpich-feedstock
  sha: d187d6d38143e3f03d0eb8a9cb0b16d23175594e
