# This file created by conda-build 24.7.1
# ------------------------------------------------

package:
  name: matplotlib-base
  version: 3.9.2
source:
  sha256: 9c49b6683a34469e6d20864c7d5b975c4f29d7c60de1ce857980bead48769c3f
  url: https://github.com/matplotlib/matplotlib/archive/v3.9.2.tar.gz
build:
  ignore_run_exports_from:
    - zlib
  number: 0
  string: py310hf02ac8c_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_0
    - gcc_impl_linux-64 12.4.0 hb2e57f8_0
    - gcc_linux-64 12.4.0 h6b7512a_0
    - gxx_impl_linux-64 12.4.0 h613a52c_0
    - gxx_linux-64 12.4.0 h8489865_0
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc-devel_linux-64 12.4.0 ha4f9413_100
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libsanitizer 12.4.0 h46f95d5_0
    - libstdcxx-devel_linux-64 12.4.0 ha4f9413_100
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libtool 2.4.7 h27087fc_0
    - ninja 1.12.1 h297d8ca_0
    - pkg-config 0.29.2 h4bc722e_1009
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h0c530f3_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.7.4 hbcca054_0
    - certifi 2024.7.4 pyhd8ed1ab_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - freetype 2.12.1 h267a509_2
    - importlib-metadata 8.2.0 pyha770c72_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libblas 3.9.0 23_linux64_openblas
    - libcblas 3.9.0 23_linux64_openblas
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 14.1.0 h77fa898_0
    - libgfortran-ng 14.1.0 h69a702a_0
    - libgfortran5 14.1.0 hc5f4f2c_0
    - libgomp 14.1.0 h77fa898_0
    - liblapack 3.9.0 23_linux64_openblas
    - libnsl 2.0.1 hd590300_0
    - libopenblas 0.3.27 pthreads_hac2b453_1
    - libpng 1.6.43 h2797004_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - meson 1.5.1 pyhd8ed1ab_1
    - meson-python 0.16.0 pyh0c530f3_0
    - ncurses 6.5 h59595ed_0
    - ninja 1.12.1 h297d8ca_0
    - numpy 2.0.1 py310hf9f9071_0
    - openssl 3.3.1 h4bc722e_2
    - packaging 24.1 pyhd8ed1ab_0
    - pip 24.2 pyhd8ed1ab_0
    - pybind11 2.13.4 py310haa687a3_0
    - pybind11-global 2.13.4 py310haa687a3_0
    - pyproject-metadata 0.8.0 pyhd8ed1ab_0
    - pyproject_hooks 1.1.0 pyhd8ed1ab_0
    - python 3.10.14 hd12c33a_0_cpython
    - python-build 1.2.1 pyhd8ed1ab_0
    - python_abi 3.10 4_cp310
    - qhull 2020.2 h434a139_5
    - readline 8.2 h8228510_1
    - setuptools 72.1.0 pyhd8ed1ab_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_0
    - setuptools_scm 8.1.0 hd8ed1ab_0
    - setuptools_scm_git_archive 1.4.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.12.2 hd8ed1ab_0
    - typing_extensions 4.12.2 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.20.0 pyhd8ed1ab_0
    - zlib 1.3.1 h4ab18f5_1
  run:
    - __glibc >=2.17,<3.0.a0
    - certifi >=2020.06.20
    - contourpy >=1.0.1
    - cycler >=0.10
    - fonttools >=4.22.0
    - freetype >=2.12.1,<3.0a0
    - kiwisolver >=1.3.1
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - numpy >=1.19,<3
    - numpy >=1.23
    - packaging >=20.0
    - pillow >=8
    - pyparsing >=2.3.1
    - python >=3.10,<3.11.0a0
    - python-dateutil >=2.7
    - python_abi 3.10.* *_cp310
    - qhull >=2020.2,<2020.3.0a0
    - tk >=8.6.13,<8.7.0a0
test:
  imports:
    - matplotlib
    - matplotlib._image
    - matplotlib._path
    - matplotlib._qhull
    - matplotlib._tri
    - matplotlib._ttconv
    - matplotlib.backends._backend_agg
    - matplotlib.backends._tkagg
    - matplotlib.ft2font
    - matplotlib.pyplot
    - mpl_toolkits
    - pylab
about:
  description: 'matplotlib is a python 2D plotting library which produces publication

    quality figures in a variety of hardcopy formats and interactive

    environments across platforms. matplotlib can be used in Python scripts,

    the Python and IPython shell (ala MATLAB or Mathematica), web

    application servers, and six graphical user interface toolkits.

    '
  dev_url: https://github.com/matplotlib/matplotlib/
  doc_url: http://matplotlib.org/contents.html
  home: http://matplotlib.org/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE/LICENSE
  license_url: http://matplotlib.sourceforge.net/users/license.html
  summary: Publication quality figures in Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240815.1.1
  recipe-maintainers:
    - dopplershift
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
  remote_url: https://github.com/conda-forge/matplotlib-feedstock
  sha: 3b97b3da9760063c7c1ae3287c8684cdd1d2662c
