# This file created by conda-build 24.5.1
# ------------------------------------------------

package:
  name: importlib_metadata
  version: 8.2.0
source:
  sha256: 72e8d4399996132204f9a16dcc751af254a48f8d1b20b9ff0f98d4a8f901e73d
  url: https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-8.2.0.tar.gz
build:
  noarch: generic
  number: 0
  string: hd8ed1ab_0
requirements:
  build: []
  run:
    - importlib-metadata >=8.2.0,<8.2.1.0a0
test:
  imports:
    - importlib_metadata
about:
  home: https://github.com/python/importlib_metadata
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library to access the metadata for a Python package
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240724.2.1
  recipe-maintainers:
    - marcelotrevisani
    - nehaljwani
    - nicoddemus
  remote_url: https://github.com/conda-forge/importlib_metadata-feedstock
  sha: 2a58b59c8bdaf44bcdbd63878cf769a47ebcb7df
