# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Aug 20 20:05:03 2023
# ------------------------------------------------

package:
  name: hdf5
  version: 1.14.2
source:
  patches:
    - patches/testh5diff.sh.in.patch
    - patches/testpar_Makefile.am.patch
  sha256: 1c342e634008284a8c2794c8e7608e2eaf26d01d445fb3dfd7f33cb2fb51ac53
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.14/hdf5-1.14.2/src/hdf5-1.14.2.tar.gz
build:
  number: '0'
  run_exports:
    - hdf5 >=1.14.2,<1.14.3.0a0 mpi_mpich_*
  string: mpi_mpich_ha2c2bf8_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.71 pl5321h2b4cb7a_1
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_1
    - ca-certificates 2023.7.22 hbcca054_0
    - gcc_impl_linux-64 12.3.0 he2b93b0_0
    - gcc_linux-64 12.3.0 h76fc315_1
    - gfortran_impl_linux-64 12.3.0 hfcedea8_0
    - gfortran_linux-64 12.3.0 h7fe76b4_1
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - gxx_impl_linux-64 12.3.0 he2b93b0_0
    - gxx_linux-64 12.3.0 h8a814eb_1
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_0
    - libgcc-ng 13.1.0 he5830b7_0
    - libgfortran5 13.1.0 h15d22d2_0
    - libgomp 13.1.0 he5830b7_0
    - libnsl 2.0.0 h7f98852_0
    - libsanitizer 12.3.0 h0f45ef3_0
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_0
    - libstdcxx-ng 13.1.0 hfd8a6a1_0
    - libtool 2.4.7 h27087fc_0
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - openssl 3.1.2 hd590300_0
    - perl 5.32.1 4_hd590300_perl5
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - c-ares 1.19.1 hd590300_0
    - ca-certificates 2023.7.22 hbcca054_0
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - libaec 1.0.6 hcb278e6_1
    - libcurl 8.2.1 hca28451_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libgcc-ng 13.1.0 he5830b7_0
    - libgfortran-ng 13.1.0 h69a702a_0
    - libgfortran5 13.1.0 h15d22d2_0
    - libgomp 13.1.0 he5830b7_0
    - libnghttp2 1.52.0 h61bc06f_0
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-ng 13.1.0 hfd8a6a1_0
    - libzlib 1.2.13 hd590300_5
    - mpi 1.0 mpich
    - mpich 4.1.2 h846660c_100
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.2 hd590300_0
    - zlib 1.2.13 hd590300_5
    - zstd 1.5.2 hfc55251_7
  run:
    - libaec >=1.0.6,<2.0a0
    - libcurl >=8.2.1,<9.0a0
    - libgcc-ng >=12
    - libgfortran-ng
    - libgfortran5 >=12.3.0
    - libstdcxx-ng >=12
    - libzlib >=1.2.13,<1.3.0a0
    - mpich >=4.1.2,<5.0a0
    - openssl >=3.1.2,<4.0a0
test:
  commands:
    - command -v h5c++
    - command -v h5pcc
    - command -v h5pfc
    - command -v h5redeploy
    - command -v h5perf_serial
    - command -v gif2h5
    - command -v h52gif
    - command -v h5copy
    - command -v h5debug
    - command -v h5diff
    - command -v h5dump
    - command -v h5import
    - command -v h5jam
    - command -v h5ls
    - command -v h5mkgrp
    - command -v h5repack
    - command -v h5repart
    - command -v h5stat
    - command -v h5unjam
    - test -f $PREFIX/lib/libhdf5${SHLIB_EXT}
    - test -f $PREFIX/lib/libhdf5_cpp${SHLIB_EXT}
    - test -f $PREFIX/lib/libhdf5_hl${SHLIB_EXT}
    - test -f $PREFIX/lib/libhdf5_hl_cpp${SHLIB_EXT}
    - h5dump --filedriver=ros3 "http://s3.amazonaws.com/hdfgroup/data/hdf5demo/tall.h5"
      | grep '^HDF5'
  files:
    - test
  requires:
    - cmake
    - gcc_linux-64 12.*
    - gfortran_linux-64 12.*
    - gxx_linux-64 12.*
    - make
    - pkg-config
    - zlib
about:
  dev_url: https://github.com/HDFGroup/hdf5
  doc_url: https://portal.hdfgroup.org/display/HDF5/HDF5
  home: https://www.hdfgroup.org/solutions/hdf5/
  license: LicenseRef-HDF5
  license_family: BSD
  license_file: COPYING
  summary: HDF5 is a data model, library, and file format for storing and managing
    data
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - astrofrog
    - davidbrochart
    - gillins
    - groutr
    - hmaarrfk
    - jakirkham
    - marcelotrevisani
    - marqh
    - ocefpaf
    - scopatz
    - varlackc
