# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 13 11:13:50 2024
# ------------------------------------------------

package:
  name: exceptiongroup
  version: 1.2.2
source:
  sha256: 47c2edf7c6738fafb49fd34290706d1a1a2f4d1c6df275526b62cbb4aa5393cc
  url: https://pypi.io/packages/source/e/exceptiongroup/exceptiongroup-1.2.2.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/exceptiongroup_1720869315914/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.7.4 hbcca054_0
    - flit-core 3.9.0 pyhd8ed1ab_1
    - flit-scm 1.7.0 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_1
    - packaging 24.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.4 h194c7f8_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.3.0 pyhd8ed1ab_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_0
    - setuptools_scm 8.1.0 hd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.12.2 hd8ed1ab_0
    - typing_extensions 4.12.2 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
test:
  commands:
    - pip check
  imports:
    - exceptiongroup
  requires:
    - pip
about:
  dev_url: https://github.com/agronholm/exceptiongroup
  doc_url: https://docs.python.org/3/library/exceptions.html
  home: https://pypi.org/project/exceptiongroup/
  license: MIT and PSF-2.0
  license_file: LICENSE
  summary: Backport of PEP 654 (exception groups)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240713.4.1
  recipe-maintainers:
    - xylar
  remote_url: https://github.com/conda-forge/exceptiongroup-feedstock
  sha: ff9fe97239a657e1fe67e56cdbd749efdd602b33
