# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jul  1 14:49:35 2024
# ------------------------------------------------

package:
  name: ipykernel
  version: 6.29.5
source:
  sha256: f093a22c4a40f8828f8e330a9c297cb93dcab13bd9678ded6de8e5cf81c56215
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-6.29.5.tar.gz
build:
  noarch: python
  number: '0'
  script:
    - /home/conda/feedstock_root/build_artifacts/ipykernel_1719845459717/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
      -m pip install . -vv --no-deps --no-build-isolation
    - /home/conda/feedstock_root/build_artifacts/ipykernel_1719845459717/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
      -m ipykernel install --sys-prefix
  script_env:
    - MIGRATING=False
  string: pyh3099207_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - asttokens 2.4.1 pyhd8ed1ab_0
    - backcall 0.2.0 pyh9f0ad1d_0
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - comm 0.2.2 pyhd8ed1ab_0
    - debugpy 1.8.2 py38h854fd01_0
    - decorator 5.1.1 pyhd8ed1ab_0
    - editables 0.5 pyhd8ed1ab_0
    - executing 2.0.1 pyhd8ed1ab_0
    - hatchling 1.25.0 pyhd8ed1ab_0
    - importlib-metadata 8.0.0 pyha770c72_0
    - importlib_metadata 8.0.0 hd8ed1ab_0
    - ipython 8.12.2 pyh41d4057_0
    - jedi 0.19.1 pyhd8ed1ab_0
    - jupyter_client 8.6.2 pyhd8ed1ab_0
    - jupyter_core 5.7.2 py38h578d9bd_0
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libedit 3.1.20191231 he28a2e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libnsl 2.0.1 hd590300_0
    - libsodium 1.0.18 h36c2ea0_1
    - libsqlite 3.46.0 hde9e2c9_0
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - matplotlib-inline 0.1.7 pyhd8ed1ab_0
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_1
    - packaging 24.1 pyhd8ed1ab_0
    - parso 0.8.4 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pexpect 4.9.0 pyhd8ed1ab_0
    - pickleshare 0.7.5 py_1003
    - pip 24.0 pyhd8ed1ab_0
    - platformdirs 4.2.2 pyhd8ed1ab_0
    - pluggy 1.5.0 pyhd8ed1ab_0
    - prompt-toolkit 3.0.47 pyha770c72_0
    - prompt_toolkit 3.0.47 hd8ed1ab_0
    - psutil 6.0.0 py38hfb59056_0
    - ptyprocess 0.7.0 pyhd3deb0d_0
    - pure_eval 0.2.2 pyhd8ed1ab_0
    - pygments 2.18.0 pyhd8ed1ab_0
    - python 3.8.19 hd12c33a_0_cpython
    - python-dateutil 2.9.0 pyhd8ed1ab_0
    - python_abi 3.8 4_cp38
    - pyzmq 26.0.3 py38ha44f8e3_0
    - readline 8.2 h8228510_1
    - setuptools 70.1.1 pyhd8ed1ab_0
    - six 1.16.0 pyh6c4a22f_0
    - stack_data 0.6.2 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - tornado 6.4.1 py38hfb59056_0
    - traitlets 5.14.3 pyhd8ed1ab_0
    - trove-classifiers 2024.5.22 pyhd8ed1ab_0
    - typing_extensions 4.12.2 pyha770c72_0
    - wcwidth 0.2.13 pyhd8ed1ab_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zeromq 4.3.5 h75354e8_4
    - zipp 3.19.2 pyhd8ed1ab_0
  run:
    - __linux
    - comm >=0.1.1
    - debugpy >=1.6.5
    - ipython >=7.23.1
    - jupyter_client >=6.1.12
    - jupyter_core >=4.12,!=5.0.*
    - matplotlib-inline >=0.1
    - nest-asyncio
    - packaging
    - psutil
    - python >=3.8
    - pyzmq >=24
    - tornado >=6.1
    - traitlets >=5.4.0
test:
  commands:
    - pip check
    - jupyter kernelspec list
  imports:
    - ipykernel
  requires:
    - curio
    - flaky
    - ipyparallel
    - matplotlib-base
    - numpy
    - pip
    - pytest >=7.0,<8
    - pytest-asyncio >=0.23.5
    - pytest-cov
    - pytest-timeout
    - python !=3.8
  source_files:
    - tests
about:
  description: 'A powerful interactive Python shell and a Jupyter kernel to work with

    Python code in Jupyter notebooks and other interactive frontends.

    '
  dev_url: https://github.com/ipython/ipykernel
  doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst
  doc_url: https://ipython.readthedocs.io
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: IPython Kernel for Jupyter
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240701.4.1
  recipe-maintainers:
    - Carreau
    - blink1073
    - bollwyvl
    - davidbrochart
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/ipykernel-feedstock
  sha: 99a0475df6f0920bfe0d5294f217bd8a7c8ee470
