# This file created by conda-build 24.7.1
# ------------------------------------------------

package:
  name: openssl
  version: 3.3.1
source:
  patches:
    - patches/0001-Give-util-mkinstallvars.pl-more-fine-grained-control.patch
    - patches/0002-Adapt-all-the-exporter-files-to-the-new-vars-from-ut.patch
    - patches/0003-Fix-cmake-generator.patch
  sha256: 777cd596284c883375a2a7a11bf5d2786fc5413255efab20c50d6ffe6d020b7e
  url: http://www.openssl.org/source/openssl-3.3.1.tar.gz
build:
  number: 3
  run_exports:
    - openssl >=3.3.1,<4.0a0
  string: hb9d3cd8_3
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_0
    - gcc_impl_linux-64 13.3.0 hfea6d02_0
    - gcc_linux-64 13.3.0 hc28eda2_0
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_100
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libsanitizer 13.3.0 heb74ff8_0
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libxcrypt 4.4.36 hd590300_1
    - make 4.4.1 hb9d3cd8_0
    - perl 5.32.1 7_hd590300_perl5
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h0c530f3_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
  run:
    - __glibc >=2.17,<3.0.a0
    - ca-certificates
    - libgcc-ng >=13
test:
  commands:
    - touch checksum.txt
    - $PREFIX/bin/openssl sha256 checksum.txt
    - pkg-config --print-errors --exact-version "3.3.1" openssl
    - if [[ "$(pkg-config --variable=prefix openssl)" == "" ]]; then exit 1; fi
  requires:
    - pkg-config
    - ripgrep
about:
  dev_url: https://github.com/openssl/openssl
  doc_url: https://docs.openssl.org/master/
  home: https://www.openssl.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  feedstock-name: openssl
  final: true
  flow_run_id: azure_20240823.3.1
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/openssl-feedstock
  sha: 8e2921c5187dc836bc9327184e8ba1c4daa266d0
