# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Aug  5 15:23:38 2024
# ------------------------------------------------

package:
  name: libtiff
  version: 4.6.0
source:
  patches:
    - patches/use_unix_io.patch
  sha256: 88b3979e6d5c7e32b50d7ec72fb15af724f6ab2cbf7e10880c360a77e4b5d99a
  url: https://download.osgeo.org/libtiff/tiff-4.6.0.tar.gz
build:
  missing_dso_whitelist:
    - /opt/X11/lib/libGL.1.dylib
    - /opt/X11/lib/libglut.3.dylib
  number: '4'
  run_exports:
    - libtiff >=4.6.0,<4.7.0a0
  string: h46a8edc_4
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_0
    - gcc_impl_linux-64 12.4.0 hb2e57f8_0
    - gcc_linux-64 12.4.0 h6b7512a_0
    - gxx_impl_linux-64 12.4.0 h613a52c_0
    - gxx_linux-64 12.4.0 h8489865_0
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc-devel_linux-64 12.4.0 ha4f9413_100
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libsanitizer 12.4.0 h46f95d5_0
    - libstdcxx-devel_linux-64 12.4.0 ha4f9413_100
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libtool 2.4.7 h27087fc_0
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h0c530f3_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - lerc 4.0.0 h27087fc_0
    - libdeflate 1.21 h4bc722e_0
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libjpeg-turbo 3.0.0 hd590300_1
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libwebp-base 1.4.0 hd590300_0
    - libzlib 1.3.1 h4ab18f5_1
    - xz 5.2.6 h166bdaf_0
    - zlib 1.3.1 h4ab18f5_1
    - zstd 1.5.6 ha6fb4c9_0
  run:
    - __glibc >=2.17,<3.0.a0
    - lerc >=4.0.0,<5.0a0
    - libdeflate >=1.21,<1.22.0a0
    - libgcc-ng >=12
    - libjpeg-turbo >=3.0.0,<4.0a0
    - libstdcxx-ng >=12
    - libwebp-base >=1.4.0,<2.0a0
    - libzlib >=1.3.1,<2.0a0
    - xz >=5.2.6,<6.0a0
    - zstd >=1.5.6,<1.6.0a0
test:
  commands:
    - test ! -f ${PREFIX}/lib/libtiff.a
    - test ! -f ${PREFIX}/lib/libtiffxx.a
    - test -f ${PREFIX}/lib/libtiff.so
    - test -f ${PREFIX}/lib/libtiffxx.so
about:
  description: 'This software provides support for the Tag Image File Format (TIFF),
    a

    widely used format for storing image data.

    '
  doc_url: http://www.libtiff.org/document.html
  home: http://www.libtiff.org/
  license: HPND
  license_file: LICENSE.md
  summary: Support for the Tag Image File Format (TIFF).
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240805.2.1
  recipe-maintainers:
    - hmaarrfk
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
  remote_url: https://github.com/conda-forge/libtiff-feedstock
  sha: bdf805284922d26990266d200a42583d1cc83021
