# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Aug 23 18:31:05 2024
# ------------------------------------------------

package:
  name: c-ares
  version: 1.33.1
source:
  sha256: 06869824094745872fa26efd4c48e622b9bd82a89ef0ce693dc682a23604f415
  url: https://github.com/c-ares/c-ares/releases/download/v1.33.1/c-ares-1.33.1.tar.gz
build:
  number: '0'
  run_exports:
    - c-ares >=1.33.1,<2.0a0
  string: heb4867d_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_0
    - cmake-no-system 3.30.2 he02047a_0
    - gcc_impl_linux-64 13.3.0 hfea6d02_0
    - gcc_linux-64 13.3.0 hc28eda2_0
    - kernel-headers_linux-64 4.18.0 he073ed8_2
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_100
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libsanitizer 13.3.0 heb74ff8_0
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - ninja 1.12.1 h297d8ca_0
    - sysroot_linux-64 2.28 he073ed8_2
  run:
    - __glibc >=2.28,<3.0.a0
    - libgcc-ng >=13
  run_constraint:
    - c-ares-static <0a0
about:
  home: https://c-ares.haxx.se/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240823.2.1
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
  remote_url: https://github.com/conda-forge/c-ares-feedstock
  sha: 1c3283f4cc27d957e873a41a4c00f09c7cbfb114
