# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Oct  9 20:58:49 2023
# ------------------------------------------------

package:
  name: h5py
  version: 3.10.0
source:
  sha256: 9cac7838ab139ec71adf721a1305b954e18efa4f80c82fcfe34e1eb9639ded29
  url: https://github.com/h5py/h5py/archive/3.10.0.tar.gz
build:
  number: '0'
  script_env: null
  string: mpi_mpich_py310h266b0aa_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_2
    - gcc_linux-64 12.3.0 h76fc315_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_2
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libsanitizer 12.3.0 h0f45ef3_2
    - libstdcxx-ng 13.2.0 h7e041cc_2
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - c-ares 1.20.1 hd590300_0
    - ca-certificates 2023.7.22 hbcca054_0
    - cython 0.29.36 py310hc6cd4ac_1
    - hdf5 1.14.2 mpi_mpich_ha2c2bf8_0
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libaec 1.1.2 h59595ed_1
    - libblas 3.9.0 18_linux64_openblas
    - libcblas 3.9.0 18_linux64_openblas
    - libcurl 8.3.0 hca28451_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_2
    - libgfortran-ng 13.2.0 h69a702a_2
    - libgfortran5 13.2.0 ha4646dd_2
    - libgomp 13.2.0 h807b86a_2
    - liblapack 3.9.0 18_linux64_openblas
    - libnghttp2 1.52.0 h61bc06f_0
    - libnsl 2.0.0 hd590300_1
    - libopenblas 0.3.24 pthreads_h413a1c8_0
    - libsqlite 3.43.0 h2797004_0
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-ng 13.2.0 h7e041cc_2
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - mpi 1.0 mpich
    - mpi4py 3.1.4 py310h30280a6_1
    - mpich 4.1.2 h846660c_100
    - ncurses 6.4 hcb278e6_0
    - numpy 1.22.4 py310h4ef5377_0
    - openssl 3.1.3 hd590300_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pkg-config 0.29.2 h36c2ea0_1008
    - pkgconfig 1.5.5 pyhd8ed1ab_4
    - python 3.10.12 hd12c33a_0_cpython
    - python_abi 3.10 4_cp310
    - readline 8.2 h8228510_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 h2797004_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.5 hfc55251_0
  run:
    - cached-property
    - hdf5 >=1.14.2,<1.14.3.0a0 mpi_mpich_*
    - libgcc-ng >=12
    - mpi4py >=3.0
    - mpich >=4.1.2,<5.0a0
    - numpy >=1.22.4,<2.0a0
    - python >=3.10,<3.11.0a0
    - python_abi 3.10.* *_cp310
test:
  commands:
    - pip check
  imports:
    - h5py
  requires:
    - pip
    - pytest
    - pytest-mpi
about:
  dev_url: https://github.com/h5py/h5py
  home: http://www.h5py.org/
  license: BSD-3-Clause
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jan-janssen
    - minrk
    - ocefpaf
    - scopatz
    - tacaswell
