# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jul 30 18:43:59 2024
# ------------------------------------------------

package:
  name: mpi4py
  version: 4.0.0
source:
  - fn: mpi4py-4.0.0.tar.gz
    sha256: 820d31ae184d69c17d9b5d55b1d524d56be47d2e6cb318ea4f3e7007feff2ccc
    url: https://github.com/mpi4py/mpi4py/releases/download/4.0.0/mpi4py-4.0.0.tar.gz
build:
  number: '1'
  run_exports:
    - mpi4py >=4.0.0,<5.0a0
  script:
    - /home/conda/feedstock_root/build_artifacts/mpi4py_1722365105243/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
      -m pip install --no-deps --no-build-isolation . -vv
  string: py310h52f6967_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_0
    - gcc_impl_linux-64 12.4.0 hb2e57f8_0
    - gcc_linux-64 12.4.0 h6b7512a_0
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc-devel_linux-64 12.4.0 ha4f9413_100
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libsanitizer 12.4.0 h46f95d5_0
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h0c530f3_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.7.4 hbcca054_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - cython 3.0.10 py310hc6cd4ac_0
    - importlib-metadata 8.2.0 pyha770c72_0
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 14.1.0 h77fa898_0
    - libgfortran-ng 14.1.0 h69a702a_0
    - libgfortran5 14.1.0 hc5f4f2c_0
    - libgomp 14.1.0 h77fa898_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - mpi 1.0 mpich
    - mpich 4.2.2 h4a7f18d_100
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4bc722e_2
    - packaging 24.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pyproject_hooks 1.1.0 pyhd8ed1ab_0
    - python 3.10.14 hd12c33a_0_cpython
    - python-build 1.2.1 pyhd8ed1ab_0
    - python_abi 3.10 4_cp310
    - readline 8.2 h8228510_1
    - setuptools 71.0.4 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zipp 3.19.2 pyhd8ed1ab_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc-ng >=12
    - mpich >=4.2.2,<5.0a0
    - python >=3.10,<3.11.0a0
    - python_abi 3.10.* *_cp310
test:
  imports:
    - mpi4py
    - mpi4py.MPI
    - mpi4py.futures
    - mpi4py.util.dtlib
    - mpi4py.util.pkl5
    - mpi4py.util.pool
    - mpi4py.util.sync
about:
  description: 'MPI for Python provides bindings of the Message Passing Interface
    (MPI)

    standard for the Python programming language, allowing any Python program

    to exploit multiple processors.

    '
  dev_url: https://github.com/mpi4py/mpi4py
  doc_url: https://mpi4py.readthedocs.org/
  home: https://mpi4py.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python bindings for MPI
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240730.2.1
  recipe-maintainers:
    - SylvainCorlay
    - dalcinl
    - davidbrochart
    - leofang
    - minrk
    - msarahan
    - ocefpaf
  remote_url: https://github.com/conda-forge/mpi4py-feedstock
  sha: 47bf6463611138dddeb40ffd977cf203d8bd449f
