# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 22 13:58:42 2023
# ------------------------------------------------

package:
  name: mpb
  version: 1.11.1
source:
  fn: mpb-1.11.1.tar.gz
  sha256: dc55b081c56079727dac92d309f8e4ea84ca6eea9122ec24b7955f8c258608e1
  url: https://github.com/NanoComp/mpb/releases/download/v1.11.1/mpb-1.11.1.tar.gz
build:
  number: '4'
  run_exports:
    - mpb * mpi_mpich_*
  string: mpi_mpich_h5eb1b22_4
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_1
    - gcc_impl_linux-64 12.3.0 he2b93b0_0
    - gcc_linux-64 12.3.0 h76fc315_1
    - gfortran_impl_linux-64 12.3.0 hfcedea8_0
    - gfortran_linux-64 12.3.0 h7fe76b4_1
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_0
    - libgcc-ng 13.1.0 he5830b7_0
    - libgfortran5 13.1.0 h15d22d2_0
    - libgomp 13.1.0 he5830b7_0
    - libsanitizer 12.3.0 h0f45ef3_0
    - libstdcxx-ng 13.1.0 hfd8a6a1_0
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - c-ares 1.19.1 hd590300_0
    - ca-certificates 2023.7.22 hbcca054_0
    - fftw 3.3.10 nompi_hc118613_108
    - hdf5 1.14.2 mpi_mpich_ha2c2bf8_0
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - libaec 1.0.6 hcb278e6_1
    - libblas 3.9.0 5_h92ddd45_netlib
    - libcblas 3.9.0 5_h92ddd45_netlib
    - libcurl 8.2.1 hca28451_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libgcc-ng 13.1.0 he5830b7_0
    - libgfortran-ng 13.1.0 h69a702a_0
    - libgfortran5 13.1.0 h15d22d2_0
    - libgomp 13.1.0 he5830b7_0
    - liblapack 3.9.0 5_h92ddd45_netlib
    - libnghttp2 1.52.0 h61bc06f_0
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-ng 13.1.0 hfd8a6a1_0
    - libzlib 1.2.13 hd590300_5
    - mpi 1.0 mpich
    - mpich 4.1.2 h846660c_100
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.2 hd590300_0
    - zstd 1.5.2 hfc55251_7
  run:
    - _openmp_mutex
    - fftw >=3.3.10,<4.0a0
    - hdf5 >=1.14.2,<1.14.3.0a0 mpi_mpich_*
    - libblas >=3.9.0,<4.0a0
    - libcblas >=3.9.0,<4.0a0
    - libgcc-ng >=12
    - libgfortran-ng
    - libgfortran5 >=12.3.0
    - liblapack >=3.9.0,<4.0a0
    - mpich >=4.1.2,<5.0a0
    - zlib
test:
  commands:
    - test -f ${PREFIX}/lib/libmpb${SHLIB_EXT}
about:
  dev_url: https://github.com/NanoComp/mpb
  doc_url: https://mpb.readthedocs.io
  home: https://github.com/NanoComp/mpb
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: MIT Photonic-Bands - computation of photonic band structures in periodic
    media
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ChristopherHogan
    - RobinD42
    - oskooi
